"""
test_ml_integration.py
======================
Test suite specifically for the ML Insight Ranker integration.
"""

import pandas as pd
import pytest
from sklearn.pipeline import Pipeline

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from insight_model import load_insight_ranker, predict_insight_scores
from schema import Col

@pytest.fixture
def mock_df():
    data = []
    # Create 5 rows with required numeric and categorical feats
    # to simulate prediction.
    for i in range(5):
        data.append({
            Col.AMOUNT: 100 * (i + 1),
            Col.AMOUNT_ZSCORE: float(i),
            Col.PERCENT_DEVIATION: 0.1 * i,
            Col.CATEGORY_CONFIDENCE: 0.9,
            Col.IS_ANOMALY: True if i == 4 else False,
            Col.IS_RECURRING: True if i == 0 else False,
            Col.IS_WEEKEND: False,
            Col.ROLLING_7D_MEAN: 100.0,
            Col.ROLLING_30D_MEAN: 100.0,
            Col.ROLLING_7D_STD: 10.0,
            Col.MONTH_SIN: 0.5,
            Col.MONTH_COS: 0.5,
            Col.AMOUNT_LOG: 4.6,
            Col.PREDICTED_CATEGORY: "food"
        })
    return pd.DataFrame(data)

def test_load_insight_ranker():
    # If the file hasn't been generated by train_and_save_models.py,
    # it might return None. Ensure it doesn't crash.
    pipeline = load_insight_ranker()
    # It should preferably be a pipeline if generated, but we gracefully handle None
    if pipeline is not None:
        assert isinstance(pipeline, Pipeline)

def test_predict_insight_scores(mock_df):
    pipeline = load_insight_ranker()
    
    # Test scoring against the pipeline
    scored_df = predict_insight_scores(pipeline, mock_df)
    
    assert Col.INSIGHT_SCORE in scored_df.columns
    assert len(scored_df) == 5
    # Scores should be floats
    assert scored_df[Col.INSIGHT_SCORE].dtype == float

def test_predict_insight_scores_graceful_fallback(mock_df):
    # Pass None explicitly
    scored_df = predict_insight_scores(None, mock_df)
    assert Col.INSIGHT_SCORE in scored_df.columns
    # all defaults should be 0.0
    assert (scored_df[Col.INSIGHT_SCORE] == 0.0).all()
